version: "3.9"

services:
  yun-cha-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3201:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    command: ["pnpm", "start"]
    # 如果需要环境变量，取消注释：
    # env_file:
    #   - .env.local
